[package]
name = "sui_move_example"
version = "0.1.0"
published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }

[addresses]
example = "0x0"
std = "0x1"
sui = "0x2"
